name: jinji-portal-copilot-main
version: 1

source:
  provider: GitHub
  properties:
    branch: main
    repository: https://github.com/nishihara1018/jinji-portal-copilot

stages:
  - name: test
    requires_approval: false
