version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
# /usr/local/bin に直接入れるのではなく、一度 temp に落として権限をつけてから移動
      - sudo curl -Lo /usr/local/bin/copilot https://github.com/aws/copilot-cli/releases/latest/download/copilot-linux
      - sudo chmod +x /usr/local/bin/copilot
      - copilot --version

  build:
    commands:
      - echo "Building services..."
      - ls -la
      - copilot --version

  post_build:
    commands:
      - ls -la
